### ISSUE TITLE
HTTP call made by library might fail & panic

### ISSUE THREAD

**Issue by exklamationmark** [customerio/go-customerio#1]
Hi, I was using the library to do some job, and was sending out events to customer.io.
My program panicked & crashed, and from the stack trace the problem seems to happen here:

https://github.com/customerio/go-customerio/blob/master/customerio.go#L120

The call `http.DefaultClient.Do(req)` might actually fail, thus produce a nil resp and an error.
In this case, the call `resp.StatusCode` will fail (nil pointer), and this panic doesn't seem to be handled.

I would suggest the following fix
```go
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return 0, nil, err // and let the caller handle the error
	}
	// else case, but since we returned earlier, we don't need a block
	defer resp.Body.Close()
	status = resp.StatusCode
	if resp.ContentLength >= 0 {
		responseBody = make([]byte, resp.ContentLength)
		resp.Body.Read(responseBody)
	}
```

**Comment by idawes** [comment]
Thanks for raising this. Fixed in https://github.com/customerio/go-customerio/commit/5c580c54b3d1027f45aefa0acff13b4ddc466d1c
