### ISSUE TITLE
Add support for user provided httpclient

### ISSUE THREAD

**Issue by mhughes** [customerio/go-customerio#17]
Hi, current implementation wraps httpclient construction to a point you cannot set timeouts.  
Ideally we would be able to inject a user supplied httpclient.

**Comment by hownowstephen** [comment]
as of v2.1.0 can now supply an optional `WithHTTPClient()` param, like

```
customerio.NewTrackClient("<siteid>", "<apikey>", customerio.WithHTTPClient(myCustomClient)
```

hope this helps!
