### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by AjdinHalac** [customerio/go-customerio#27]
Support for [context](https://pkg.go.dev/context) package should be added.

Package context defines the Context type, which carries deadlines, cancellation signals, and other request-scoped values across API boundaries and between processes.

This will allow proper context propagation towards customerIO.
However, where context propagation is not necessary, context.TODO() can be used.

**Comment by joepurdy** [comment]
@AjdinHalac we added support for contexts in #32 which was released as [v3.3.0](https://github.com/customerio/go-customerio/releases/tag/v3.3.0).

We haven't provided the best documentation around using the functions that support contexts so I'll leave this open just a bit longer and close it out once we've done a better job at documenting these methods.
