### ISSUE TITLE
Fix tests to use a mock instead of live API tokens

### ISSUE THREAD

**Issue by hownowstephen** [customerio/go-customerio#8]
The current implementation of our tests for this library requires a live token and sends requests directly to Customer.io. This is bad testing practice!

We should instead point our existing tests at mock servers in the same way as our other client libraries, which also allows us to then hook the library to run tests automatically in Travis

**Comment by joepurdy** [comment]
This was fixed in #21 with the addition of a mock `httptest.NewServer`
